version: '3.7'
services:
  web_server:
    build: .
    ports:
      - "5000:8000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_ENDPOINT=${WEATHER_API_ENDPOINT}
      - SOUND_PATH=/app/sounds
      - CONFIG_PATH=${CONFIG_PATH}
      - ROCKET_SECRET_KEY=${ROCKET_SECRET_KEY}
    volumes:
      - ./backend/sounds_pokemon:/app/sounds
      - ./backend/config:/app/config
      - ./tmp:/tmp_sounds
