FROM golang:1.15.15-alpine3.14 as builder

WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o main .

# Backend
FROM alpine:3.14

RUN apk update && apk upgrade && apk add --no-cache ffmpeg

ENV DB_PATH=data/db.bin
ENV SOUNDS_PATH=/tmp/sounds

RUN mkdir /tmp/sounds

WORKDIR /app

RUN mkdir data

COPY --from=builder /app/main main

ENTRYPOINT [ "/app/main" ]
